Dev
brainstormforce/bb-timeline pull request #2
Opened 2017-01-11 05:41 UTC by bhushanb20

Version 1.0.1 - new feature added for date / custom content

2017-03-21 05:06 UTC, Nikschavan requested changes

2017-03-21 05:06 UTC, Nikschavan commented on readme.txt
> +Tested up to: 4.6
@bhushanb20 update the latest WordPress version for tested up to.

2017-03-21 05:06 UTC, Nikschavan commented on readme.txt
> +
The newer versions should be above in the changelog.

2017-03-21 05:06 UTC, Nikschavan commented on readme.txt
> +This version added new options. Upgrade immediately for more timeline design possibility.
No need to add an upgrade notice.

2017-03-21 05:06 UTC, Nikschavan commented on timeline-for-beaver-builder-module/css/frontend.css
> +    margin-bottom: 0 !important;
Is it possible to not use `!important`?

2017-03-21 05:06 UTC, Nikschavan commented on timeline-for-beaver-builder-module/css/frontend.css
> +    /*top: 10px;*/
if this CSS is not required, delete it, don't commit commented code.

2017-03-21 05:06 UTC, Nikschavan commented on timeline-for-beaver-builder-module/timeline-for-beaver-builder-module.php
> +                    //'title'         => __( 'Date', 'bb-timeline' ),
Don't commit commented code.

2017-03-21 06:07 UTC, Nikschavan commented
@bhushanb20 The PHPCS requirements are also required to be fixed before we merge this.

2017-03-21 10:25 UTC, bhushanb20 commented on readme.txt
> +Tested up to: 4.6
I have updated the WordPress version tested up 4.7

2017-03-21 10:29 UTC, bhushanb20 commented on readme.txt
> +
I have listed versions from most recent at top to oldest at bottom.

2017-03-21 10:30 UTC, bhushanb20 commented on readme.txt
> +This version added new options. Upgrade immediately for more timeline design possibility.
I have removed update notice

2017-03-21 10:35 UTC, bhushanb20 commented on timeline-for-beaver-builder-module/css/frontend.css
> +    /*top: 10px;*/
Done

2017-03-21 10:36 UTC, bhushanb20 commented on timeline-for-beaver-builder-module/css/frontend.css
> +    margin-bottom: 0 !important;
I have removed !important from css

2017-03-21 10:38 UTC, bhushanb20 commented on timeline-for-beaver-builder-module/timeline-for-beaver-builder-module.php
> +                    //'title'         => __( 'Date', 'bb-timeline' ),
Removed commented code

2017-03-27 05:13 UTC, Nikschavan approved these changes

2017-04-10 03:55 UTC, merged